#this function is used to write the input file
import os
import sys
import numpy as np
import glob, os

from pyearth.system.define_global_variables import *

from pyearth.toolbox.reader.line_count import line_count
from pyearth.toolbox.reader.text_reader_string import text_reader_string
def swat_write_watershed_input_file(oSwat_in):
    """
    write the input files from the new parameter generated by PEST to each hru file
    """
    aParameter_watershed = oSwat_in.aParameter_watershed
    
    nParameter_watershed = oSwat_in.nParameter_watershed
    if(nParameter_watershed<1):        
        print("There is no watershed parameter to be updated!")
        return
    else:
        pass    
    
    iFlag_simulation = oSwat_in.iFlag_simulation
    iFlag_calibration = oSwat_in.iFlag_calibration

    
    sWorkspace_simulation_case = oSwat_in.sWorkspace_simulation_case
    sWorkspace_simulation_copy =  oSwat_in.sWorkspace_simulation_copy

    sWorkspace_calibration_case = oSwat_in.sWorkspace_calibration_case
    sWorkspace_pest_model = sWorkspace_calibration_case
    print('sWorkspace_simulation_copy: ' + sWorkspace_simulation_copy)


    # we need to identify a list of files that are HRU defined, you can add others later
    #for watershed parameter, only one file extension is used so far
    aExtension = ['.bsn','.wwq']
    aBSN=['SFTMP','SMTMP']
    aWWQ=['AI0']


    aExtension = np.asarray(aExtension)
    nFile_type= len(aExtension)

    #the parameter is located in the different files
    aParameter_table = np.empty( (nFile_type)  , dtype = object )

    #need a better way to control this 
    for iVariable in range(nParameter_watershed):
        sParameter_watershed = aParameter_watershed[iVariable]

        if sParameter_watershed in aBSN:
            if( aParameter_table[0] is None  ):
                aParameter_table[0] = np.array(sParameter_watershed)
            else:
                aParameter_table[0] = np.append(aParameter_table[0],sParameter_watershed)
                #aParameter_table[0].append(sParameter_watershed) 
            pass
        else:
            if sParameter_watershed in aWWQ:
                if( aParameter_table[1] is None  ):
                    aParameter_table[1] = sParameter_watershed
                else:
                    aParameter_table[1].append(sParameter_watershed) 
                pass
            pass
                        

    aParameter_user = np.full( (nFile_type) , None , dtype = np.dtype(object) )
    aParameter_count = np.full( (nFile_type) , 0 , dtype = int )
    aParameter_flag = np.full( (nFile_type) , 0 , dtype = int )
    aParameter_index = np.full( (nFile_type) , -1 , dtype = np.dtype(object) )
  
    #then we need to define what parameters may be calibrated
    #this list should include all possible parameters in the parameter file
  
    #read parameter file
    if iFlag_simulation == 1:
        sFilename_parameter = sWorkspace_simulation_case + slash + 'watershed.para'
    else:
        iFlag_debug = 0
        sPath_current = os.getcwd()
        sFilename_parameter = sPath_current + slash + 'watershed.para'

    print(sFilename_parameter)
    #check whetheher the file exist or not
    if os.path.isfile(sFilename_parameter):
        pass
    else:
        print('The file does not exist: '+sFilename_parameter)
        return

    aData_all = text_reader_string(sFilename_parameter, cDelimiter_in =',')
    aDummy = aData_all[0,:]
    nParameter = len(aDummy) - 1
    aParameter_list = aDummy[1: nParameter+1]

    aParameter_value = (aData_all[1,1: nParameter+1]).astype(float)
    aParameter_value = np.array(aParameter_value)
    print(aParameter_value)
    
    for p in range(0, nParameter):
        para = aParameter_list[p]
        for i in range(0, nFile_type):
            aParameter_tmp = aParameter_table[i]
            if aParameter_tmp is not None:
                if para in aParameter_tmp:
                    aParameter_count[i]= aParameter_count[i]+1
                    aParameter_flag[i]=1

                    if(aParameter_count[i] ==1):
                        aParameter_index[i] = [p]
                        aParameter_user[i]= [para]
                    else:
                        aParameter_index[i] = np.append(aParameter_index[i],[p])
                        aParameter_user[i] = np.append(aParameter_user[i],[para])
                    continue

    
    if iFlag_simulation == 1:
        sWorkspace_source_case = sWorkspace_simulation_copy
        sWorkspace_target_case = sWorkspace_simulation_case
        pass
    else:
        sPath_current = os.getcwd()
        if (os.path.normpath(sPath_current)  == os.path.normpath(sWorkspace_pest_model)):
            print('this is the parent, no need to copy anything')
            return
        else:
            print('this is a child')
            sWorkspace_source_case = sWorkspace_simulation_copy
            sWorkspace_target_case = sPath_current
    
    for iFile_type in range(0, nFile_type):
        sExtension = aExtension[iFile_type]
        iFlag = aParameter_flag[iFile_type]
        if( iFlag == 1):
            #there should be only one for each extension       
            
            sFilename = 'basins' + sExtension
            sFilename_watershed = sWorkspace_source_case + slash + sFilename
                
            #open the file to read

            nline = line_count(sFilename_watershed)
            ifs=open(sFilename_watershed, 'rb')   
            
            #open the new file to write out
            sFilename_watershed_out = sWorkspace_target_case + slash + sFilename            

            if os.path.exists(sFilename_watershed_out):                
                os.remove(sFilename_watershed_out)

            ofs=open(sFilename_watershed_out, 'w') 
            aValue = aParameter_value[:]
            for iLine in range(nline):
                sLine0=(ifs.readline())
                if len(sLine0) < 1:
                    continue
                sLine0=sLine0.rstrip()
                #print(sLine0)
                sLine= sLine0.decode("utf-8", 'ignore')
                
                
                for i in range(0, aParameter_count[iFile_type]):
                    aParameter_indices = np.array(aParameter_index[iFile_type])
                    aParameter_filetype = np.array(aParameter_user[iFile_type])
                    if 'sftmp' in sLine.lower() and 'SFTMP' in aParameter_filetype : 
                        dummy = 'SFTMP'   
                        dummy_index1 = np.where(aParameter_filetype == dummy)
                        dummy_index2 = aParameter_indices[dummy_index1][0]
                        sLine_new = "{:16.3f}".format(  aValue[dummy_index2]  )     + '    | pest parameter SFTMP' + '\n'
                        ofs.write(sLine_new)
                        print(sLine_new)
                        break #important
                    else:
                        if 'smtmp' in sLine.lower() and 'SMTMP' in aParameter_filetype: 
                            dummy = 'SMTMP'                             
                            dummy_index1 = np.where(aParameter_filetype == dummy)
                            dummy_index2 = aParameter_indices[dummy_index1][0]
                            sLine_new = "{:16.3f}".format(  aValue[dummy_index2]  )     + '    | pest parameter SMTMP' + '\n'
                            ofs.write(sLine_new)
                            print(sLine_new)
                            break  #important
                        else:
                            sLine = sLine + '\n'
                            ofs.write(sLine)
                            break  #important
                            

                
            
            ifs.close()
            ofs.close()

    print('Finished writing watershed file!')
    return    

    