
from swaty.auxiliary.swaty_generate_template_configuration_json_file import swaty_generate_template_configuration_json_file

sFilename_json = '/global/homes/l/liao313/workspace/python/swaty/tests/configuration/swat_simulation.json'
swaty_generate_template_configuration_json_file(sFilename_json)